In [1]:
import pandas as pd

In [2]:
sept= pd.read_csv("JC-202009-citibike-tripdata.csv")
sept.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,45656,Subscriber,1992,1
1,193,2020-09-01 00:49:00.7370,2020-09-01 00:52:14.3640,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,45352,Subscriber,1991,1
2,273,2020-09-01 00:51:44.5870,2020-09-01 00:56:17.7160,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,44424,Subscriber,1969,1
3,1419,2020-09-01 00:52:48.3160,2020-09-01 01:16:28.0490,3203,Hamilton Park,40.727596,-74.044247,3270,Jersey & 6th St,40.725289,-74.045572,42240,Subscriber,1986,1
4,254,2020-09-01 00:56:16.7170,2020-09-01 01:00:31.0870,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,42434,Subscriber,1992,1

In [3]:
oct=pd.read_csv("JC-202010-citibike-tripdata.csv")
oct.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,156,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,42293,Subscriber,1996,1
1,143,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44740,Subscriber,1998,1
2,305,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,-74.050389,41369,Subscriber,1988,2
3,1097,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,-74.057271,42285,Customer,2001,1
4,277,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,45231,Subscriber,1965,1

In [4]:
nov=pd.read_csv("JC-202011-citibike-tripdata.csv")
nov.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,756,2020-11-01 00:11:32.6250,2020-11-01 00:24:09.5850,3275,Columbus Drive,40.718355,-74.038914,3225,Baldwin at Montgomery,40.723659,-74.064194,42436,Subscriber,1984,1
1,584,2020-11-01 00:14:20.4820,2020-11-01 00:24:04.7820,3681,Grand St,40.715178,-74.037683,3209,Brunswick St,40.724176,-74.050656,46532,Customer,1969,0
2,403,2020-11-01 00:22:55.8820,2020-11-01 00:29:39.0950,3203,Hamilton Park,40.727596,-74.044247,3483,Montgomery St,40.719420,-74.050990,35139,Subscriber,1980,1
3,498,2020-11-01 00:41:37.4270,2020-11-01 00:49:55.7010,3268,Lafayette Park,40.713464,-74.062859,3213,Van Vorst Park,40.718489,-74.047727,46539,Customer,1969,0
4,151,2020-11-01 00:53:21.2340,2020-11-01 00:55:52.8060,3185,City Hall,40.717733,-74.043845,3276,Marin Light Rail,40.714584,-74.042817,44388,Subscriber,1986,1

In [6]:
tableau_df1=pd.merge(sept, oct, on="tripduration", how="left")
tableau_df1

,tripduration,starttime_x,stoptime_x,start station id_x,start station name_x,start station latitude_x,start station longitude_x,end station id_x,end station name_x,end station latitude_x,...,start station latitude_y,start station longitude_y,end station id_y,end station name_y,end station latitude_y,end station longitude_y,bikeid_y,usertype_y,birth year_y,gender_y
0,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.714584,-74.042817,3205.0,JC Medical Center,40.716540,-74.049638,42213.0,Subscriber,1990.0,1.0
1,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.726012,-74.050389,3273.0,Manila & 1st,40.721651,-74.042884,44697.0,Subscriber,1990.0,1.0
2,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.725726,-74.071959,3679.0,Bergen Ave,40.722104,-74.071455,44973.0,Subscriber,1989.0,1.0
3,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.725340,-74.067622,3225.0,Baldwin at Montgomery,40.723659,-74.064194,41696.0,Subscriber,1990.0,1.0
4,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.716540,-74.049638,3185.0,City Hall,40.717733,-74.043845,44389.0,Subscriber,1983.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051389,418,2020-10-13 15:12:31.7920,2020-10-13 15:19:30.5280,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,...,40.733670,-74.062500,3677.0,Glenwood Ave,40.727551,-74.071061,39421.0,Subscriber,1991.0,1.0
1051390,418,2020-10-13 15:12:31.7920,2020-10-13 15:19:30.5280,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,...,40.721525,-74.046305,3638.0,Washington St,40.724294,-74.035483,42396.0,Subscriber,1984.0,1.0
1051391,418,2020-10-13 15:12:31.7920,2020-10-13 15:19:30.5280,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,...,40.716540,-74.049638,3214.0,Essex Light Rail,40.712774,-74.036486,15999.0,Subscriber,1991.0,2.0
1051392,418,2020-10-13 15:12:31.7920,2020-10-13 15:19:30.5280,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,...,40.716540,-74.049638,3681.0,Grand St,40.715178,-74.037683,47108.0,Subscriber,1988.0,2.0
1051393,418,2020-10-13 15:12:31.7920,2020-10-13 15:19:30.5280,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,...,40.714584,-74.042817,3211.0,Newark Ave,40.721525,-74.046305,33677.0,Customer,1969.0,0.0

In [11]:
tableau_df1 = tableau_df1.rename(columns={'Oct_start_time':'Sept_start_time', 'Oct_stop_time':'Sept_stop_time',
                                         'Oct_start_station_id':'Sept_start_station_id', 'Oct_start_station_name':
                                         'Sept_start_station_name','Oct_start_lat':'Sept_start_lat',
                                         'Oct_start_long': 'Sept_start_long', 'Oct_end_station_d':
                                         'Sept_end_station_d', 'Oct_end_station_name': 'Sept_end_station_name',
                                         'Oct_end_lat': "Sept_end_lat", 'Oct_end_long':
                                         'Sept_end_long'})
tableau_df1.head()

,tripduration,Sept_start_time,Sept_stop_time,Sept_start_station_id,Sept_start_station_name,Sept_start_lat,Sept_start_long,Sept_end_station_d,Sept_end_station_name,Sept_end_lat,...,start station latitude_y,start station longitude_y,end station id_y,end station name_y,end station latitude_y,end station longitude_y,bikeid_y,usertype_y,birth year_y,gender_y
0,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.714584,-74.042817,3205.0,JC Medical Center,40.716540,-74.049638,42213.0,Subscriber,1990.0,1.0
1,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.726012,-74.050389,3273.0,Manila & 1st,40.721651,-74.042884,44697.0,Subscriber,1990.0,1.0
2,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.725726,-74.071959,3679.0,Bergen Ave,40.722104,-74.071455,44973.0,Subscriber,1989.0,1.0
3,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.725340,-74.067622,3225.0,Baldwin at Montgomery,40.723659,-74.064194,41696.0,Subscriber,1990.0,1.0
4,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.716540,-74.049638,3185.0,City Hall,40.717733,-74.043845,44389.0,Subscriber,1983.0,1.0

In [13]:
tableau_df1 = tableau_df1.rename(columns={'start station latitude_y':'Oct_start_lat', 'start station longitude_y':
                                          'Oct_start_long', 'end station id_y': 'Oct_end_station_id', 'end station name_y':
                                          'Oct_end_station_name', 'end station latitude_y': 'Oct_end_lat', 'end station longitude_y':
                                          'Oct_end_long', 'bikeid_y': 'bike_id', 'usertype_y': 'usertype', 'birth year_y': 
                                          'birthyear', 'gender_y': 'gender'})
tableau_df1.head()

,tripduration,Sept_start_time,Sept_stop_time,Sept_start_station_id,Sept_start_station_name,Sept_start_lat,Sept_start_long,Sept_end_station_d,Sept_end_station_name,Sept_end_lat,...,Oct_start_lat,Oct_start_long,Oct_end_station_id,Oct_end_station_name,Oct_end_lat,Oct_end_long,bike_id,usertype,birthyear,gender
0,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.714584,-74.042817,3205.0,JC Medical Center,40.716540,-74.049638,42213.0,Subscriber,1990.0,1.0
1,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.726012,-74.050389,3273.0,Manila & 1st,40.721651,-74.042884,44697.0,Subscriber,1990.0,1.0
2,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.725726,-74.071959,3679.0,Bergen Ave,40.722104,-74.071455,44973.0,Subscriber,1989.0,1.0
3,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.725340,-74.067622,3225.0,Baldwin at Montgomery,40.723659,-74.064194,41696.0,Subscriber,1990.0,1.0
4,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.716540,-74.049638,3185.0,City Hall,40.717733,-74.043845,44389.0,Subscriber,1983.0,1.0

In [14]:
tableau_df2=pd.merge(tableau_df1, nov, on="tripduration", how="left")
tableau_df2.head()

,tripduration,Sept_start_time,Sept_stop_time,Sept_start_station_id,Sept_start_station_name,Sept_start_lat,Sept_start_long,Sept_end_station_d,Sept_end_station_name,Sept_end_lat,...,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype_y,birth year,gender_y
0,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.730897,-74.063913,3194.0,McGinley Square,40.725340,-74.067622,28426.0,Subscriber,1984.0,1.0
1,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.724294,-74.035483,3275.0,Columbus Drive,40.718355,-74.038914,47257.0,Subscriber,1989.0,1.0
2,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.737711,-74.066921,3220.0,5 Corners Library,40.734961,-74.059503,42343.0,Subscriber,1978.0,1.0
3,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.728745,-74.032108,3199.0,Newport Pkwy,40.728745,-74.032108,27705.0,Customer,1999.0,2.0
4,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.719586,-74.043117,3270.0,Jersey & 6th St,40.725289,-74.045572,43974.0,Subscriber,1982.0,2.0

In [15]:
tableau_df2 = tableau_df2.rename(columns={'starttime':'Nov_start_time','stoptime':'Nov_stoptime',
                                          'start station id': 'Nov_start_station_id', 'start station name':
                                          'Nov_start_station_name', 'start station latitude':'Nov_start_lat',
                                          'start station longitude':'Nov_start_long', 'end station id':'Nov_end_id',
                                          'end station name':'Nov_end_station_name','end station latitude':'Nov_end_lat',
                                          'end station longitude':'Nov_end_long','usertype_y':'usertype','gender_y':'gender'})
tableau_df2.head()

,tripduration,Sept_start_time,Sept_stop_time,Sept_start_station_id,Sept_start_station_name,Sept_start_lat,Sept_start_long,Sept_end_station_d,Sept_end_station_name,Sept_end_lat,...,Nov_start_lat,Nov_start_long,Nov_end_id,Nov_end_station_name,Nov_end_lat,Nov_end_long,bikeid,usertype,birth year,gender
0,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.730897,-74.063913,3194.0,McGinley Square,40.725340,-74.067622,28426.0,Subscriber,1984.0,1.0
1,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.724294,-74.035483,3275.0,Columbus Drive,40.718355,-74.038914,47257.0,Subscriber,1989.0,1.0
2,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.737711,-74.066921,3220.0,5 Corners Library,40.734961,-74.059503,42343.0,Subscriber,1978.0,1.0
3,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.728745,-74.032108,3199.0,Newport Pkwy,40.728745,-74.032108,27705.0,Customer,1999.0,2.0
4,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,40.719586,-74.043117,3270.0,Jersey & 6th St,40.725289,-74.045572,43974.0,Subscriber,1982.0,2.0

In [16]:
tableau_df2.to_csv("tableau_hw.csv", encoding='utf-8')